-- Weekly engagement: Player of the Week + Man of the Match (org-scoped, last 7 days).
-- Weekly score = avg match rating*10 + goals*4 + assists*2 + training attendance*3.
-- (Full function body applied via Supabase; see project migration weekly_highlights.)
